package ahodanenok.nand2tetris.jack;

public enum TokenType {

    VBAR, AMPERSAND, PLUS, MINUS, STAR,
    SLASH, EQUAL, TILDE, DOT, COMMA, SEMICOLON,
    LEFT_ANGLE, RIGHT_ANGLE,
    LEFT_BRACKET, RIGHT_BRACKET,
    LEFT_PAREN, RIGHT_PAREN,
    LEFT_BRACE, RIGHT_BRACE,
    STRING, INTEGER, IDENTIFIER, KEYWORD,
    CLASS, CONSTRUCTOR, FUNCTION, METHOD, FIELD,
    STATIC, VAR, INT, CHAR, BOOLEAN, VOID, TRUE,
    FALSE, NULL, THIS, LET, DO, IF, ELSE, WHILE,
    RETURN;
}
